services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "256G"
      DISK_TYPE: "ide"
      RAM_SIZE: "14G"
      CPU_CORES: "8"
      USERNAME: "Hoang"
      PASSWORD: "Dztop1vn"
      ARGUMENTS: "-drive file=/driver.iso,media=cdrom"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 5900:5900/udp
      - 5900:5900/tcp
    volumes:
      - ./windows:/storage
      - /isos/a.iso:/custom.iso
      - /isos/driver.iso:/driver.iso
    restart: always
    stop_grace_period: 2m
