services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://dn720003.ca.archive.org/0/items/ghost-spectre-windows-10/2009.SUPERLITE%2BCOMPACT.X64.U2.GHOSTSPECTRE.(N).ISO"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows-data:/data
    restart: always
    stop_grace_period: 2m
